name: Release

on:
  release: 
    types: [prereleased, published]

permissions:
  contents: write
  pull-requests: write
  repository-projects: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          make test

      - name: Release
        id: release
        run: |
          echo "Creating a release..."
          GOPROXY=proxy.golang.org go list -m github.com/caesar-rocks/mail@${{ github.event.release.tag_name }}
          echo "Release created!"