name: Test Code

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    name: ${{ matrix.os }} Go (${{ matrix.go }})
    timeout-minutes: 10
    strategy:
      matrix:
        go: ['stable','oldstable']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Check go version
        run: go version

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod Verify
        run: go mod verify

      - name: Run tests
        run: |
          make test

